INSERT INTO USERS(LOGIN_ID,PASSWORD,ENABLED) VALUES ('admin', '$2a$10$MFNKDnq7EgpoxxylzwbJPePKSXJqN7pbtF062EMXxJ4sq9Ibnf8lW', TRUE );
INSERT INTO AUTHORITIES(LOGIN_ID, ROLE) VALUES ('admin', 'ADMIN');